# Heroes of Pymoli Data Analysis

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load
file_to_load = r"C:\Users\Mabel\Downloads\purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
original_df = pd.read_csv(file_to_load)



In [2]:
# See the shape of my data frame
original_df.shape

(780, 7)

In [3]:
# See the first 5 rows of my data frame
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price  
0  Extraction, Quickblade Of Trembling Hands   3.53  
1                          Frenzied Scimitar   1.56  
2                               Final Critic   4.88  
3                                Blindscythe   3.27  
4                                       Fury   1.44

# Player Count

In [4]:
# Display the total number of players
total_players = original_df.SN.nunique()
print(total_players)

576


In [5]:
# Display the total number of players
playercount_df = pd.DataFrame({"Total Players":[total_players]})
playercount_df

Total Players
0            576

# Purchasing Analysis (Total)

In [6]:
#Number of Unique Items
num_unique_item = original_df["Item ID"].nunique()
print(num_unique_item)

183


In [7]:
#Average Purchase Price
aveg_purchase_price = original_df["Price"].mean()
print(aveg_purchase_price)

3.050987179487176


In [8]:
#Total Number of Purchases
num_purchases = original_df["Purchase ID"].count()
print(num_purchases)

780


In [9]:
# Total Revenue
total_revenue = original_df["Price"].sum()
print(total_revenue)

2379.77


In [10]:
#Create a data frame
purchasingTotal_df = pd.DataFrame({
    "Number of Unique Items":[num_unique_item],
    "Average Price":[aveg_purchase_price],
    "Number of Purchases":[num_purchases],
    "Total Revenue":[total_revenue]
    })
#Formats the two dollar value columns Average Price and Total Revenue
purchasingTotal_df["Average Price"] = purchasingTotal_df["Average Price"].map("${:.2f}".format)
purchasingTotal_df["Total Revenue"] = purchasingTotal_df["Total Revenue"].map("${:.2f}".format)
                                
purchasingTotal_df

Number of Unique Items Average Price  Number of Purchases Total Revenue
0                     183         $3.05                  780      $2379.77

# Gender Demographics

In [11]:
#Assigned the filtered column to a variable
original_df.groupby(["Gender"]).nunique()


Purchase ID   SN  Age  Gender  Item ID  Item Name  \
Gender                                                                     
Female                         113   81   22       1       90         90   
Male                           652  484   39       1      182        178   
Other / Non-Disclosed           15   11    8       1       13         13   

                       Price  
Gender                        
Female                    79  
Male                     144  
Other / Non-Disclosed     12

In [12]:
# The dataframe was filtered by two columns
original_df.groupby(["Gender"])["SN"].nunique()

Gender
Female                    81
Male                     484
Other / Non-Disclosed     11
Name: SN, dtype: int64

In [13]:
# Assigned the filtered df to a variable and listed the values
gendervalue = original_df.groupby(["Gender"])["SN"].nunique().values
gendervalue

array([ 81, 484,  11], dtype=int64)

In [14]:
# Assigned a variable for a list of the gender names
gendername = list(original_df.groupby(["Gender"])["SN"].nunique().index)
gendername

['Female', 'Male', 'Other / Non-Disclosed']

In [15]:
# Calculate the percentage
genderpercent=gendervalue/gendervalue.sum()
genderpercent

array([0.140625  , 0.84027778, 0.01909722])

In [16]:
# Create a dataframe
genderSummary = pd.DataFrame()
print(genderSummary)

Empty DataFrame
Columns: []
Index: []


In [17]:
# Populate the dataframe
genderSummary["GenderNames"] = gendername
print(genderSummary)

             GenderNames
0                 Female
1                   Male
2  Other / Non-Disclosed


In [18]:
#Populate the rest of the dataframe
genderSummary["Total Count"] = gendervalue
genderSummary["Percentage of Players"] = genderpercent * 100

#Sort the Total Count
genderSummary = genderSummary.sort_values(by="Total Count",ascending=False)

#Formats the one column to two decimal place.
genderSummary["Percentage of Players"] = genderSummary["Percentage of Players"].map("{:.2f}".format)

#Set Gendernames as Index
genderSummary=genderSummary.set_index("GenderNames")
print(genderSummary)

                       Total Count Percentage of Players
GenderNames                                             
Male                           484                 84.03
Female                          81                 14.06
Other / Non-Disclosed           11                  1.91


# Purchasing Analysis (Gender)

In [19]:
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price  
0  Extraction, Quickblade Of Trembling Hands   3.53  
1                          Frenzied Scimitar   1.56  
2                               Final Critic   4.88  
3                                Blindscythe   3.27  
4                                       Fury   1.44

In [20]:
# Filtered it by two columns and got the values
purchase_data = original_df.groupby(["Gender"])["Purchase ID"].nunique().values
purchase_data

array([113, 652,  15], dtype=int64)

In [21]:
# Calculate the Average purchase Price per Gender
avegprice=original_df.groupby(["Gender"])["Price"].mean().values
avegprice

array([3.20300885, 3.01785276, 3.346     ])

In [22]:
# Calculate the total value per Gender
totalpurchase = purchase_data * avegprice
totalpurchase

array([ 361.94, 1967.64,   50.19])

In [23]:
# Calculate the Average Purchase Total per Person by Gender
avegtotal = totalpurchase / gendervalue
avegtotal

array([4.46839506, 4.0653719 , 4.56272727])

In [24]:
#Create a data frame
purchaseAG = pd.DataFrame()
purchaseAG["Gender"] = gendername
purchaseAG["Purchase Count"] = purchase_data
purchaseAG["Average Purchase Price"] = avegprice
purchaseAG["Total Purchase Value"] = totalpurchase
purchaseAG["Aveg Total Purchase per Person"] = avegtotal

# Set GenderName as Index
purchaseAG = purchaseAG.set_index("Gender")

#Formats the two dollar value columns Average Price and Total Revenue
purchaseAG["Average Purchase Price"] = purchaseAG["Average Purchase Price"].map("${:.2f}".format)
purchaseAG["Total Purchase Value"] = purchaseAG["Total Purchase Value"].map("${:.2f}".format)
purchaseAG["Aveg Total Purchase per Person"] = purchaseAG["Aveg Total Purchase per Person"].map("${:.2f}".format)

print(purchaseAG)

                       Purchase Count Average Purchase Price  \
Gender                                                         
Female                            113                  $3.20   
Male                              652                  $3.02   
Other / Non-Disclosed              15                  $3.35   

                      Total Purchase Value Aveg Total Purchase per Person  
Gender                                                                     
Female                             $361.94                          $4.47  
Male                              $1967.64                          $4.07  
Other / Non-Disclosed               $50.19                          $4.56  


# Age Demographics

In [25]:
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price  
0  Extraction, Quickblade Of Trembling Hands   3.53  
1                          Frenzied Scimitar   1.56  
2                               Final Critic   4.88  
3                                Blindscythe   3.27  
4                                       Fury   1.44

In [26]:
# Create the age bins
bins=[0,10,14,19,24,29,34,39,200]
# Create the name of the bins
group_name = ["<10","10-14","15-19","20-24","25-29","30-34","35-39","40+"]

In [27]:
# Appended the Age Bin to the original dataframe
original_df["Age Bin"] = pd.cut(original_df["Age"],bins,labels=group_name)
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price Age Bin  
0  Extraction, Quickblade Of Trembling Hands   3.53   20-24  
1                          Frenzied Scimitar   1.56     40+  
2                               Final Critic   4.88   20-24  
3                                Blindscythe   3.27   20-24  
4                                       Fury   1.44   20-24

In [28]:
# The Count for each Age Bin
bincount = original_df.groupby(["Age Bin"])["SN"].nunique().values
bincount

array([ 24,  15, 107, 258,  77,  52,  31,  12], dtype=int64)

In [29]:
# Sum of the Total Count
bintotal = bincount.sum()
bintotal

576

In [30]:
#Calculate the percentage of players
percentplayer = bincount/bintotal*100
percentplayer

array([ 4.16666667,  2.60416667, 18.57638889, 44.79166667, 13.36805556,
        9.02777778,  5.38194444,  2.08333333])

In [31]:
#Create a data frame
agedemoDF = pd.DataFrame()
agedemoDF["Age Bin"] = group_name
agedemoDF["Total Count"] = bincount
agedemoDF["Percentage of Players"] = percentplayer
# Set Age Bin as Index
agedemoDF = agedemoDF.set_index("Age Bin")
#Formats the column to two decimal points
agedemoDF["Percentage of Players"] = agedemoDF["Percentage of Players"].map("{:.2f}".format)

print(agedemoDF)

         Total Count Percentage of Players
Age Bin                                   
<10               24                  4.17
10-14             15                  2.60
15-19            107                 18.58
20-24            258                 44.79
25-29             77                 13.37
30-34             52                  9.03
35-39             31                  5.38
40+               12                  2.08


# Purchasing Analysis (Age)

In [32]:
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price Age Bin  
0  Extraction, Quickblade Of Trembling Hands   3.53   20-24  
1                          Frenzied Scimitar   1.56     40+  
2                               Final Critic   4.88   20-24  
3                                Blindscythe   3.27   20-24  
4                                       Fury   1.44   20-24

In [33]:
# Filtered the dataframe to get the count per each age bin
purchasect = original_df.groupby(["Age Bin"])["Purchase ID"].nunique().values
purchasect

array([ 32,  19, 136, 365, 101,  73,  41,  13], dtype=int64)

In [34]:
# Filtered dataframe by age bin and price then get the mean values
purchaseaveg = original_df.groupby(["Age Bin"])["Price"].mean().values
purchaseaveg

array([3.405     , 2.68157895, 3.03595588, 3.05221918, 2.9009901 ,
       2.93150685, 3.60170732, 2.94153846])

In [35]:
# Calculate the total purchase value
tpurchaseval = purchasect * purchaseaveg
tpurchaseval

array([ 108.96,   50.95,  412.89, 1114.06,  293.  ,  214.  ,  147.67,
         38.24])

In [36]:
# Calculate the Average Total Purchase per Person
avegTPperperson = tpurchaseval / bincount
avegTPperperson

array([4.54      , 3.39666667, 3.85878505, 4.31806202, 3.80519481,
       4.11538462, 4.76354839, 3.18666667])

In [37]:
#Create a data frame
purchaseSummary = pd.DataFrame()

In [38]:
# Fill dataframe
purchaseSummary["Age Bin"] = group_name
purchaseSummary["Purchase Count"] = purchasect
purchaseSummary["Average Purchase Price"] = purchaseaveg
purchaseSummary["Total Purchase Value"] = tpurchaseval
purchaseSummary["Avg Total Purchase per Person"] = avegTPperperson

# Set Age Bin as Index
purchaseSummary = purchaseSummary.set_index("Age Bin")

#Formats the column to two decimal points with $ sign in front
purchaseSummary["Average Purchase Price"] = purchaseSummary["Average Purchase Price"].map("${:.2f}".format)
purchaseSummary["Total Purchase Value"] = purchaseSummary["Total Purchase Value"].map("${:.2f}".format)
purchaseSummary["Avg Total Purchase per Person"] = purchaseSummary["Avg Total Purchase per Person"].map("${:.2f}".format)

print(purchaseSummary)

         Purchase Count Average Purchase Price Total Purchase Value  \
Age Bin                                                               
<10                  32                  $3.40              $108.96   
10-14                19                  $2.68               $50.95   
15-19               136                  $3.04              $412.89   
20-24               365                  $3.05             $1114.06   
25-29               101                  $2.90              $293.00   
30-34                73                  $2.93              $214.00   
35-39                41                  $3.60              $147.67   
40+                  13                  $2.94               $38.24   

        Avg Total Purchase per Person  
Age Bin                                
<10                             $4.54  
10-14                           $3.40  
15-19                           $3.86  
20-24                           $4.32  
25-29                           $3.81  
30-34    

# Top Spenders

In [39]:
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price Age Bin  
0  Extraction, Quickblade Of Trembling Hands   3.53   20-24  
1                          Frenzied Scimitar   1.56     40+  
2                               Final Critic   4.88   20-24  
3                                Blindscythe   3.27   20-24  
4                                       Fury   1.44   20-24

In [57]:
spenderSN = original_df.groupby(["SN"])["Purchase ID"].nunique()
result = spenderSN.sort_values(ascending=False)
result.head()

SN
Lisosia93      5
Iral74         4
Idastidru52    4
Aina42         3
Iri67          3
Name: Purchase ID, dtype: int64

In [41]:
avegprice = original_df.groupby(["SN"])["Price"].mean()
avegprice.head()

SN
Adairialis76    2.28
Adastirin33     4.48
Aeda94          4.91
Aela59          4.32
Aelaria33       1.79
Name: Price, dtype: float64

In [42]:
totalpurval = original_df.groupby(["SN"])["Price"].sum()
totalpurval.head()

SN
Adairialis76    2.28
Adastirin33     4.48
Aeda94          4.91
Aela59          4.32
Aelaria33       1.79
Name: Price, dtype: float64

In [58]:
#Create a data frame
spenderSummary = pd.DataFrame({"Purchase Count":spenderSN, "Average Purchase Price":avegprice.map("${:.2f}".format), "Total Purchase Value":totalpurval})
sortSummary = spenderSummary.sort_values(["Total Purchase Value"], ascending=False)
sortSummary.head()


Purchase Count Average Purchase Price  Total Purchase Value
SN                                                                      
Lisosia93                 5                  $3.79                 18.96
Idastidru52               4                  $3.86                 15.45
Chamjask73                3                  $4.61                 13.83
Iral74                    4                  $3.40                 13.62
Iskadarya95               3                  $4.37                 13.10

# Most Popular Items

In [59]:
original_df.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price Age Bin  
0  Extraction, Quickblade Of Trembling Hands   3.53   20-24  
1                          Frenzied Scimitar   1.56     40+  
2                               Final Critic   4.88   20-24  
3                                Blindscythe   3.27   20-24  
4                                       Fury   1.44   20-24

In [68]:
filteddata = original_df.loc[:,["Item ID","Item Name","Price"]]
filteddata

Item ID                                     Item Name  Price
0        108     Extraction, Quickblade Of Trembling Hands   3.53
1        143                             Frenzied Scimitar   1.56
2         92                                  Final Critic   4.88
3        100                                   Blindscythe   3.27
4        131                                          Fury   1.44
5         81                                     Dreamkiss   3.61
6        169        Interrogator, Blood Blade of the Queen   2.18
7        162                                 Abyssal Shard   2.67
8         21                                     Souleater   1.10
9        136                  Ghastly Adamantite Protector   3.58
10        95                         Singed Onyx Warscythe   4.74
11       162                                 Abyssal Shard   2.67
12       116                       Renewed Skeletal Katana   4.18
13         4                            Bloodlord's Fetish   1.70
14       165                   Bone Crushing Silver Skewer   4.86
15        98                   Deadline, Voice Of Subtlety   2.89
16        40                                 Second Chance   2.52
17       161                                        Devine   1.76
18        82                                       Nirvana   4.90
19        89             Blazefury, Protector of Delusions   4.64
20        57               Despair, Favor of Due Diligence   4.60
21       168           Sun Strike, Jaws of Twisted Visions   1.48
22        24                                 Warped Fetish   3.81
23       151                                     Severance   3.40
24       141                                    Persuasion   3.19
25       178  Oathbreaker, Last Hope of the Breaking Storm   4.23
26        71                                        Demise   1.61
27        96                   Blood-Forged Skeletal Spine   3.09
28       119     Stormbringer, Dark Blade of Ending Misery   4.32
29        37           Shadow Strike, Glory of Ending Hope   3.16
..       ...                                           ...    ...
750      167                   Malice, Legacy of the Queen   3.61
751      180                                   Stormcaller   3.36
752      112                                  Worldbreaker   2.60
753      178  Oathbreaker, Last Hope of the Breaking Storm   4.23
754       79                           Alpha, Oath of Zeal   4.05
755       76                      Haunted Bronzed Bludgeon   3.15
756       73                                   Ritual Mace   2.05
757       57               Despair, Favor of Due Diligence   4.60
758      182                                     Toothpick   4.03
759       72                                 Winter's Bite   3.77
760       44                         Bonecarvin Battle Axe   2.38
761       17                  Lazarus, Terror of the Earth   1.70
762      110                                    Suspension   1.44
763       85                                Malificent Bag   1.75
764      113                             Solitude's Reaver   4.07
765      130                                         Alpha   2.07
766       58             Freak's Bite, Favor of Holy Might   4.14
767       92                                  Final Critic   4.88
768       92                                  Final Critic   4.88
769      145                          Fiery Glass Crusader   4.58
770       12                                         Dawne   1.02
771       25                                     Hero Cane   4.35
772      136                  Ghastly Adamantite Protector   3.58
773       19                 Pursuit, Cudgel of Necromancy   1.02
774      101                                  Final Critic   4.19
775       60                                          Wolf   3.54
776      164                              Exiled Doomblade   1.63
777       67         Celeste, Incarnation of the Corrupted   3.46
778      101                                 

In [75]:
purchasecount = filteddata.groupby(["Item ID",'Item Name'])["Item Name"].count()
purchasecount

Item ID  Item Name                                   
0        Splinter                                         4
1        Crucifer                                         3
2        Verdict                                          6
3        Phantomlight                                     6
4        Bloodlord's Fetish                               5
5        Putrid Fan                                       4
6        Rusty Skull                                      2
7        Thorn, Satchel of Dark Souls                     7
8        Purgatory, Gem of Regret                         3
9        Thorn, Conqueror of the Corrupted                4
10       Sleepwalker                                      4
11       Brimstone                                        5
12       Dawne                                            6
13       Serenity                                         4
14       Possessed Core                                   2
15       Soul Infused Crystal                 

In [76]:
itempurchase = filteddata.groupby(["Item ID",'Item Name'])["Price"].sum()
print(itempurchase)

Item ID  Item Name                                   
0        Splinter                                         5.12
1        Crucifer                                         9.78
2        Verdict                                         14.88
3        Phantomlight                                    14.94
4        Bloodlord's Fetish                               8.50
5        Putrid Fan                                      16.32
6        Rusty Skull                                      7.40
7        Thorn, Satchel of Dark Souls                     9.31
8        Purgatory, Gem of Regret                        11.79
9        Thorn, Conqueror of the Corrupted               10.92
10       Sleepwalker                                      7.16
11       Brimstone                                       18.25
12       Dawne                                            6.12
13       Serenity                                         5.64
14       Possessed Core                                   5.22
1

In [77]:
avegprice = filteddata.groupby(["Item ID",'Item Name'])["Price"].mean()
print(avegprice)

Item ID  Item Name                                   
0        Splinter                                        1.28
1        Crucifer                                        3.26
2        Verdict                                         2.48
3        Phantomlight                                    2.49
4        Bloodlord's Fetish                              1.70
5        Putrid Fan                                      4.08
6        Rusty Skull                                     3.70
7        Thorn, Satchel of Dark Souls                    1.33
8        Purgatory, Gem of Regret                        3.93
9        Thorn, Conqueror of the Corrupted               2.73
10       Sleepwalker                                     1.79
11       Brimstone                                       3.65
12       Dawne                                           1.02
13       Serenity                                        1.41
14       Possessed Core                                  2.61
15       Soul In

In [78]:
itemSummary = pd.DataFrame({"Purchase Count":purchasecount, "Item Price":avegprice.map("${:.2f}".format), "Total Purchase Value":itempurchase})
itemSummary = itemSummary.sort_values(["Purchase Count"], ascending=False)
itemSummary.head()

Purchase Count  \
Item ID Item Name                                                      
178     Oathbreaker, Last Hope of the Breaking Storm              12   
145     Fiery Glass Crusader                                       9   
108     Extraction, Quickblade Of Trembling Hands                  9   
82      Nirvana                                                    9   
19      Pursuit, Cudgel of Necromancy                              8   

                                                     Item Price  \
Item ID Item Name                                                 
178     Oathbreaker, Last Hope of the Breaking Storm      $4.23   
145     Fiery Glass Crusader                              $4.58   
108     Extraction, Quickblade Of Trembling Hands         $3.53   
82      Nirvana                                           $4.90   
19      Pursuit, Cudgel of Necromancy                     $1.02   

                                                      Total Purchase Value  
Item ID Item Name                                                           
178     Oathbreaker, Last Hope of the Breaking Storm                 50.76  
145     Fiery Glass Crusader                                         41.22  
108     Extraction, Quickblade Of Trembling Hands                    31.77  
82      Nirvana                                                      44.10  
19      Pursuit, Cudgel of Necromancy                                 8.16

# Most Profitable Items

In [79]:
mostprof = itemSummary.sort_values(["Total Purchase Value"], ascending=False)
mostprof.head()

Purchase Count  \
Item ID Item Name                                                      
178     Oathbreaker, Last Hope of the Breaking Storm              12   
82      Nirvana                                                    9   
145     Fiery Glass Crusader                                       9   
92      Final Critic                                               8   
103     Singed Scalpel                                             8   

                                                     Item Price  \
Item ID Item Name                                                 
178     Oathbreaker, Last Hope of the Breaking Storm      $4.23   
82      Nirvana                                           $4.90   
145     Fiery Glass Crusader                              $4.58   
92      Final Critic                                      $4.88   
103     Singed Scalpel                                    $4.35   

                                                      Total Purchase Value  
Item ID Item Name                                                           
178     Oathbreaker, Last Hope of the Breaking Storm                 50.76  
82      Nirvana                                                      44.10  
145     Fiery Glass Crusader                                         41.22  
92      Final Critic                                                 39.04  
103     Singed Scalpel                                               34.80